name: trainer
version: 1.0
main_config: &main
    seed: !!int 42
    metrics:
        - binary_auroc
        - accuracy
    device:
        name: 'cpu'

train: &train
    # Change to different value if not using max_steps
    <<: *main
    # Can add the max_epochs vs max_steps functionality
    max_steps: !!int 2
    eval_interval: !!int 1
    loader_params:
        batch_size: !!int 10
        num_workers: !!int 4
        shuffle: true
    optimizer:
        type: adam_w
        params:
            lr: !!float 1e-2
            betas: [0.9,0.998]
            eps: !!float 1e-8
    scheduler:
        type: cosine_warm
        params:
            T_0: !!int 1
            T_mult: !!int 2
            eta_min: !!float 1e-7
    criterion:
        type: cross_entropy
        params:
    log:
        log_interval: !!int 1
        logger_params:
            model: unimodal
            trainer: trainer
            comment: "Trial for Logger and Trainer"
            log_dir: './logs/train'
        values:
            loss: true
            metrics: true
            # hparams: true

eval:
    <<: *main
    max_steps: !!int 2
    loader_params:
        batch_size: !!int 4
        num_workers: !!int 4
        shuffle: false
    log:
        logger_params:
            model: unimodal
            trainer: trainer
            comment: "Trial for Logger and Trainer"
            log_dir: './logs/eval'
        values:
            # loss: true
            metrics: true
            # hparams: true
