trainig_config: &trainig_config
  epochs: 85
  batch_size: 32
  learning_params:
    init_lr: 1e-4
    optimizer_params:
       optimizer:
         name: AdamW
         beta_1: 0.9
         beta_2: 0.98
         eps: 1e-8
                
    decay_params:


resnet152: &resnet152
  model:
    model_name: resnet152
    classification_layers: 2
  data_config:
    resize_shape: (224,224)
    normalize:
      mean: (0.485, 0.456, 0.406)
      std: (0.229, 0.224, 0.225)
