data_dir: /content/drive/My Drive/Hateful-Memes-Challenge/data
images:
    train: /content/drive/My Drive/Hateful-Memes-Challenge/data/
    dev: /content/drive/My Drive/Hateful-Memes-Challenge/data/
    test: /content/drive/My Drive/Hateful-Memes-Challenge/data/
annotations:
    train: /content/drive/My Drive/Hateful-Memes-Challenge/data/train.jsonl
    dev: /content/drive/My Drive/Hateful-Memes-Challenge/data/dev.jsonl
    test: /content/drive/My Drive/Hateful-Memes-Challenge/data/test.jsonl
get_image: true
get_text: false
image_processor:
    type: torchvision
    params:
        - type: Resize
          params:
            size: [224,224]
            interpolation: BICUBIC
        - type: ToTensor
          params: null # Need to write it at as null if no parameters are passed,
        - type: Normalize
          params:
            mean: [0.485,0.456,0.406]
            std: [0.229,0.224,0.225]
